

const CHANGE_USER_STATE = 'CHANGE_USER_STATE'
const CHANGE_MENU_CONFIG = 'CHANGE_MENU_CONFIG'
const CHANGE_NEW = 'CHANGE_NEW'
const CHANGE_THOER = 'CHANGE_THOER'
const CHANGE_WORD = 'CHANGE_WORD'
const CHANGE_MONEY = 'CHANGE_MONEY'

export { CHANGE_USER_STATE , CHANGE_MENU_CONFIG,CHANGE_NEW,CHANGE_THOER,CHANGE_WORD,CHANGE_MONEY }